   # numpy initialize

In [1]:
import numpy as np
np.array([1,4,2,5,3]) 
# use array to build a numpy, both of them can only accept the same data type
type(np) #module
#NumPy is a module for Python

module

In [2]:
# numpy initalize, different from list which is a=[] assign a list type to variable a
#np itself is the variable , to be exactly, it is a module. you can assign np to a variable but it is no different using numpy
import numpy as np
#numpy transform different datatype to the biggest datatype
np.array([3.14,2,3,4,5])
# all integer become float


array([3.14, 2.  , 3.  , 4.  , 5.  ])

In [3]:
np.array([3.14,2,3,4,5],dtype=int)
#set datatype=integer and the float is transform to integer

array([3, 2, 3, 4, 5])

In [4]:
# numpy can be multi=dimension
np.array([range(i,i+3) for i in[2,4,6]])
# insides np.array use for loop can shape a multi-dimension numpy.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# use full to make multi-dimension
np.full((3,5),10)  # make a np with 3 dimension and each dimension has 5 elements
#in full, the basket is (), in array the basket is []

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [6]:
#give numpy default values
np.zeros(10) # give np 10 element and default value is 0
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.linspace(0,1,5) #make a numpy with 5 elements and values is between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.random(10)
# random is a module and random.random is a function to a random array
# random default values between 0 and 1
np.random.normal(0,10,10) # 值是常態分配 加總是0 標準差是1

array([ -3.29794603,   3.41552314,   7.51516741,   5.43627254,
        14.53163295,  -6.68754852,  28.08044734,  -7.48764824,
       -14.84875619,  -0.22361019])

In [9]:
np.eye(7,dtype=int) # make a 7 dimension numpy with 7 element in each array and the values is unpredictable \
# but the values is all float and you can use dtype to transform the datatype

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [10]:
np.empty(5) # make a one dimension numpy with five elements and the values is also unpredictable
# the values is also all float

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5)) # 3=3 subarray and each subarray have 4 columns and 5 rows
#the number of elements of every dimension called shape the total number called size
print(x1.ndim) # ndim means the dimenstion of x1
print(x2.ndim)
print(x3.shape) # (3,4,5) is the expression of the description of line2
print(x3.ndim)
print(x3.size)# 60=3*4*5
x3

1
2
(3, 4, 5)
3
60


array([[[2, 7, 0, 3, 9],
        [7, 8, 3, 2, 3],
        [6, 8, 6, 5, 7],
        [6, 3, 4, 3, 6]],

       [[8, 0, 5, 1, 3],
        [3, 5, 5, 3, 2],
        [8, 5, 0, 1, 9],
        [5, 0, 0, 3, 7]],

       [[4, 2, 1, 1, 0],
        [4, 7, 7, 3, 0],
        [6, 0, 5, 0, 9],
        [0, 1, 4, 8, 4]]])

In [12]:
np.random.randint(10,size=6) # random from 0~10
np.arange(10) # arrange 0~9 in order

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy operation

In [13]:
# it can work as a list, but everyone is a str
import json
np.array(['str','2','3.14'])
#numpy cannot saved as json file because np is module ,json can not save module object
# with open("test.json", "w", encoding="utf-8") as file:
    # file.write(json.dumps(np, ensure_ascii=False, indent=4))

array(['str', '2', '3.14'], dtype='<U4')

In [14]:
# operation sub array
x=np.arange(10)
x
x[:5] #[start:stop:step] this is means 0~4
x[5:] #this means start from index 5 which is 6th element
x[::-1] # start from tail and the result is reverse the array
x[5::-1] # start from the 6th element and reverse as well
type(x)

numpy.ndarray

# 用mgrid會比一般array多一層

In [15]:
x2=np.random.randint(10,size=(3,4))
x2
x2[:2,:3] # start from the first subarray and start from the 3rd element in each subarray
# the values will change because the parent array is a random array
x2[:,0] #1st subarray and from the first element
x2[:] #the whole array, because by default, it is from first to the end
x,y= np.mgrid[:4:, :10:] #把每一層都當一維,內容是element,然後element裡可以再有element
x,y #裡面2個array (因為xy)每個element再有4個element,最後一層的element有10個element
    # values is 0 for the first element and 3 for the last element 
a=np.mgrid[:4:, :10:] # has different meanings, 
a # 裡面1個array (因為a)
a[0][:,0] # access first column
a[0][0,:] # access first row

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 子陣列是父陣列的point 改了子陣列就等於改了父陣列

In [16]:
#陣列複製 不會動到原陣列
x2=np.random.randint(10,size=(3,4))
print(x2)
x2_sub_copy=x[:2,:2].copy()
x2_sub_copy[0,0]=42
print(x2)

[[2 0 9 9]
 [3 4 7 0]
 [2 0 4 1]]
[[2 0 9 9]
 [3 4 7 0]
 [2 0 4 1]]


# column(欄)是垂直的 row(列)是水平的 column在前 row在後


In [17]:
#reshape
grid=np.arange(0,10).reshape((2,5)) # reshape 前後 size數要符合 否則報錯
grid

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
x=np.array([1,2,3,4])#==>[1, 2, 3,4]
x
x.reshape((1,4))#==>[[1,2,3,4]]=>2維有 1 column 1 row
x.reshape(2,2) #==>[[1,2],
#                   [3,4]]==>2維有2 columns 2 rows
x[np.newaxis,:]

array([[1, 2, 3, 4]])

 # newaxis無法變更原有的row數

# 陣列的分割跟合併

In [19]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [20]:
grid=np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid])  # 預設是按欄合併
np.concatenate([grid,grid],axis=1) #這樣會變列合併
#vstack = 預設合併 hstack = 列合併

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# 預設是按欄合併

In [21]:
x=np.array([1,2,3,99,99,3,2,1])
x1,x2=np.split(x,[2]) 
x1, x2
x1,x2,x3=np.split(x,[2,3])
#[]是分割點 有幾個分割點就會分出N+1個array

# 預設是按列切割

# UFUNCS Numpy 算術運算
### np.add, np.substract, np.multiply, np.divide,np.mod(取餘數) np.power(指數運算)

# 統計運算 
### sum, max,min

# Broadcasting

In [22]:
import numpy as np
a=np.array([0,1,2])
a+5

array([5, 6, 7])

# MASK

In [44]:
import datetime
import numpy
from googleapiclient.discovery import build
np.zeros(11)
youtube = build('youtube','v3',developerKey = 'AIzaSyCLNdL_6bmA5Gmqyp7u160DBZhF7iBqZ-s')
request = youtube.search().list(q='ironman4',part='snippet',type='comment',maxResults=2)
res = request.execute()
for item in res['items']:
  np.append({
    'publishedAT': item['snippet']['publishedAt'],
  })  





TypeError: append() missing 1 required positional argument: 'values'